### ISSUE TITLE
Empty overall

### ISSUE THREAD

**Issue by alimozdemir** [huang-julien/nitro-applicationinsights#16]
Hi,

I just enabled this library in my project however, I have issues with the logs.

![image](https://github.com/huang-julien/nitro-applicationinsights/assets/4493134/af2af02d-c06b-431a-b985-275adf98ceab)

It does not respect to name of the log and not group it.  Do you have any idea how to fix it? I haven't customized anything, I just enabled it and deployed it, let me know if you need any more information.

Best,

**Comment by huang-julien** [comment]
Hi yes, it is fixed but i haven't realesed 0.2.1 yet.

**Comment by alimozdemir** [comment]
Thank you! Could you tell me what is the estimated date of the new release?

**Comment by huang-julien** [comment]
Probably today or tomorrow, i'm doing some tests and releasing it afterwards :+1:

**Comment by huang-julien** [comment]
btw in the meantime you can use `'applicationinsights:trackRequest:before'` hook, the second parameter allows you to change the tracking object. 

you can set `trackInfo[event.$appInsights.client.context.keys.operationName]: trackInfo.name`

event is the event request

**Comment by alimozdemir** [comment]
Thank you, fixed!
