### ISSUE TITLE
fetchInterceptors and undefined values

### ISSUE THREAD

**Issue by robert-phillips1** [huang-julien/nitro-applicationinsights#48]
I am using the fetchInterceptors to track my dependencies, but i'm finding some of the values are turning up in app insights as undefined.  For example in onResponse:

```
name: `${context.options.method} ${context.response.url}}`,
```

both method (if one wasn't provided) and context.response.url return undefined.

**Comment by huang-julien** [comment]
hmmm that's weird. Are you able to provide a minimal reproduction through stackblitz ? 
https://stackblitz.com/edit/unjs-nitro-starter-zziw9t?file=README.md&title=Nitro%20Starter

I just need to reproduce it to see what's going on
