### ISSUE TITLE
inline `applicationinsights` as ESM module

### ISSUE THREAD

**Issue by pi0** [huang-julien/nitro-applicationinsights#59]
(related: #58) 

Hi. Following up issues reported re CJS/ESM syntax detection, and the fact that [applicationinsights](https://www.npmjs.com/package/applicationinsights/v/3.0.0-beta.12?activeTab=code) even for v3 is using legacy syntax, i would suggest to either move it to upstream issue or we can simply use unbuild setup to inline `applicationinsights` as a pure ESM module.

Please let me know if you like me to try a PR for this :)

**Comment by huang-julien** [comment]
Hi :wave: there's already an [upstream issue](https://github.com/microsoft/ApplicationInsights-node.js/issues/1205) in app insights which didn't get any answer from the team.

I'd love to get a PR from you 🤩 !

This is probably the last fix before moving to nitro modules :grin:
